[profile.default]
solc = '0.8.19'
via_ir = false
src = 'src'
test = 'test'
libs = ['lib']
out = 'out'
optimizer = true
optimizer_runs = 200
ignored_error_codes = []
fs_permissions = [{ access = "read", path = "./out-optimized" }]

[fuzz]
runs = 500

[invariant]
runs = 500
fail_on_revert = true
depth = 10

[profile.optimized-build]
via_ir = true
test = 'src'
out = 'out-optimized'

[profile.optimized-test]
src = 'test'

[profile.optimized-test-deep]
src = 'test'

[profile.optimized-test-deep.fuzz]
runs = 10000

[profile.optimized-test-deep.invariant]
runs = 5000
depth = 32

[profile.deep.fuzz]
runs = 10000

[profile.deep.invariant]
runs = 5000
depth = 32

[fmt]
line_length = 115
wrap_comments = true

[rpc_endpoints]
mainnet = "${RPC_URL_MAINNET}"
goerli = "${RPC_URL_GOERLI}"


# See more config options https://github.com/foundry-rs/foundry/tree/master/config
