name: Seaport Test CI

on: [push, pull_request]

concurrency:
 group: ${{github.workflow}}-${{github.ref}}
 cancel-in-progress: true

jobs:
 build:
   name: Build Artifacts
   runs-on: ubuntu-latest

   strategy:
     matrix:
       node-version: [16.x]

   steps:
     - uses: actions/checkout@v3
     - name: Use Node.js
       uses: actions/setup-node@v3
       with:
         node-version: ${{ matrix.node-version }}
         cache: 'yarn'
     - run: yarn install
     - run: cp .env.sample .env
     - run: yarn build

 test:
   name: Run Tests
   runs-on: ubuntu-latest

   strategy:
     matrix:
       node-version: [16.x]

   steps:
     - uses: actions/checkout@v3
     - name: Use Node.js
       uses: actions/setup-node@v3
       with:
         node-version: ${{ matrix.node-version }}
         cache: 'yarn'
     - run: yarn install
     - run: cp .env.sample .env
     - run: yarn build
     - run: yarn test
