################################################################################
##                             Network interface                              ##
################################################################################
server:
    # Address to which we bind (default: 127.0.0.1)
    address: "0.0.0.0"
    # Port on which we bind (default: 3000)
    port: 3000

################################################################################
##                               Database options                             ##
################################################################################
database:
    host: 127.0.0.1
    user: root
    database: db
    password: "12345678"
    port: 5432
    # maximum number of clients the pool should contain
    max: 20
    # number of milliseconds to wait before timing out when connecting a new client
    connectionTimeoutMillis: 10000

################################################################################
##                               Logging options                              ##
################################################################################
logging:
    # The name of the folder where the logs are stored.
    folder: logs/
    # Values: error, warn, info, http, verbose, debug, silly
    level: http
    # Default to false
    console: true

################################################################################
##                               Scheduler                                    ##
################################################################################
scheduler:
    enable: true
    items:
        - name: voter
          enable: true
          interval: 300

voter:
    deposit_contract_address: "${DEPOSIT_CONTRACT_ADDRESS}"
