# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [develop, main]
  pull_request:
    branches: [develop, main]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MNEMONIC: ${{ secrets.MNEMONIC }}
      MAINNET_RPC_URL: ${{ secrets.MAINNET_RPC_URL }}
      TESTNET_PRIVATE_KEY: ${{ secrets.TESTNET_PRIVATE_KEY }}
      MAINNET_PRIVATE_KEY: ${{ secrets.MAINNET_PRIVATE_KEY }}
      ROPSTEN_RPC_URL: ${{ secrets.ROPSTEN_RPC_URL }}
      RINKEBY_RPC_URL: ${{ secrets.RINKEBY_RPC_URL }}
      BSC_RPC_URL: ${{ secrets.BSC_RPC_URL }}
      BSC_TESTNET_RPC_URL: ${{ secrets.BSC_TESTNET_RPC_URL }}
      POLYGON_RPC_URL: ${{ secrets.POLYGON_RPC_URL }}
      MUMBAI_RPC_URL: ${{ secrets.MUMBAI_RPC_URL }}
      ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
    strategy:
      matrix:
        node-version: [12.x, 14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
      - run: yarn
      - run: yarn lint:check
      - run: yarn compile
      - run: yarn test
