version: '2.4'
services:
    postgres:
        image: postgres:12.0
        container_name: postgres
        restart: always
        environment:
            - POSTGRES_PASSWORD=pass
            - POSTGRES_USER=postgres
            - POSTGRES_DB=db
            - PGDATA=/postgresql/data
        volumes:
            - db:/postgresql/data
        ports:
            - "5432:5432"
volumes:
    db:
