/* Autogenerated file. Do not edit manually. */
// @ts-nocheck
/* tslint:disable */
/* eslint-disable */

import * as Circuits from ".";

declare module "hardhat/types/runtime" {
  interface HardhatZKit {
    getCircuit(name: "Commitment"): Promise<Circuits.Commitment>;
  }
}
