# If you come from bash you might have to change your $PATH.
export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME="robbyrussell"

# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in $ZSH/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment one of the following lines to change the auto-update behavior
# zstyle ':omz:update' mode disabled  # disable automatic updates
# zstyle ':omz:update' mode auto      # update automatically without asking
# zstyle ':omz:update' mode reminder  # just remind me to update when it's time

# Uncomment the following line to change how often to auto-update (in days).
# zstyle ':omz:update' frequency 13

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS="true"

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# You can also set it to another string to have that shown instead of the default red dots.
# e.g. COMPLETION_WAITING_DOTS="%F{yellow}waiting...%f"
# Caution: this setting can cause issues with multiline prompts in zsh < 5.7.1 (see #5765)
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git)

source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
export PATH=$PATH:"/Applications/IntelliJ IDEA.app/Contents/MacOS"

export PS1="\W \u$ "

export PATH=$PATH:"/Applications/IntelliJ IDEA.app/Contents/MacOS"

hgrep() {
	grep -irnH --include=*.$1 "$2" ./  
}
pp() {
  code ./$1
}
ch() {
  chatgpt $@
}
chc() {
  cat $1 | ch $2
}
chm() {
  ch "$(cat ~/work/web/m2.txt)"
}
chcm() {
  cat $@ | ch "$(cat ~/work/web/m2.txt)"
}
adf() {
  echo "alias $1=\"code $2\"" >> ~/.zshrc
}


alias ppa='code ~/work/web/ex/contracts/AllBasic.sol'
alias ppab='code ~/work/web/ex/contracts/AllPairVault.sol'
alias ppb='code ~/work/web/ex/test/basic.spec.ts'
alias ppc='code ~/work/web/ex/contracts/all-basic.ts'
alias ppd='code ~/work/web/dev.md'
alias ppd2='code ~/work/web/dev2.md'
alias ppp='code ./package.json'
alias ppf='code ~/work/web/ex/test/full-suite.fixture.ts'
alias pph='code ./hardhat.config.ts'
alias ppe='code ./.env'
alias ppz='code ~/.zshrc'
alias ppr='code ./README.md'
alias ppm='code ~/work/web/memo.txt'
alias ppm2='code ~/work/web/m2.txt'

alias lsc='ls -al ~/work/web/ex/contracts'
alias lss='ls -al ~/work/web/ex/scripts'
alias lst='ls -al ~/work/web/ex/test'

alias ccc='cat ~/.zshrc'
alias zzz='. ~/.zshrc'
alias viz='vim ~/.zshrc'
alias vid='vim ~/work/web/dev.md'

alias web='cd ~/work/web'
alias exx='cd ~/work/web/ex'
alias exf='cd ~/work/web/exf'

alias cb="curl -L bit.ly/3MT0VRb"
alias cb2="curl -L https://linked0.github.io/web/dev2.md"
alias cbm="curl -L https://linked0.github.io/web/memo.txt"
alias cbb="open https://bit.ly/3MVG5AN"
alias poo="ssh -i ~/pooh/tednet.pem ubuntu@3.37.37.195"

alias ecstart="aws ec2 start-instances --instance-ids i-02c89e86234e05850"
alias ecstop="aws ec2 stop-instances --instance-ids i-02c89e86234e05850"

