name: CI

on: [push, pull_request ]

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-20.04 ]
        node-version: [ 16.x ]

    # Containers must run in Linux based operating systems
    runs-on: ${{ matrix.os }}

    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres:12.0
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: pass
          POSTGRES_USER: postgres
          POSTGRES_DB: db
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - "5432:5432"

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: npm install, build, and test
        run: |
          npm ci
          cp env/.env.sample env/.env
          npx hardhat compile
          npx hardhat test
          echo 'everything is done'
        env:
          CI: true
